### ISSUE TITLE
Retarget to Replugged

### ISSUE THREAD

**Issue by Infinidoge** [LavaDesu/powercord-overlay#11]
Since Powercord has been declared End of Life, it is no longer maintained.

Replugged appears to be the fork that has arisen, and it is probably a good idea to retarget the `powercord` input to its repository:
https://github.com/replugged-org/replugged

**Comment by LavaDesu** [comment]
I'm not sure about retargeting the input to the new fork directly; making a new derivation and deprecating or removing the old one sounds like a better option, just to make people aware that the maintainers have changed and we're using a fork.

**Comment by LunNova** [comment]
https://github.com/LunNova/replugged-nix-flake/commits/main - feel free to copy/pull in the relevant changes here if it helps!

I wanted to restructure things in a backwards incompatible way so I could [get a bunch of overrides/redundant derivations out of my system flake](https://github.com/LunNova/nixos-configs/commit/1af1a7f63c15b99a4aea216f19d9f37ec9b47540) so I didn't make this as a PR - IME maintainers usually don't like it when you rewrite things like this if it isn't strictly necessary :P - but if you actually like my changes rather than finding them annoying I could also just PR them.

**Comment by Infinidoge** [comment]
I'll go ahead and make a PR to add it to this repo

Intending to do:
- `drvs/replugged-unwrapped.nix`
- `drvs/replugged.nix`
- `misc/replugged.patch`
- `misc/replugged-yarn.lock`
- `misc/yarn.lock -> misc/powercord-yarn.lock`

While otherwise keeping the structure the same.
(I suppose `index.js` would need editing too)
